project:
  type: book
  output-dir: docs/

book:
  title: "STREAM"
  subtitle: "Strategic Technology Readiness for Environmental Assessment and Management"
  author: "Andrew Owen Barker"
  date: "13/03/2025"
  chapters:
    - index.qmd
    - 01 executive-summary.qmd
    - part: "Framework Report"
      chapters: 
      - 02a - introduction.qmd
      - 02b - foundations.qmd
      - 02c - structure.qmd
      - 02d - methodology.qmd
      - 02e - maturity.qmd
      - 02f - roadmap.qmd
      - 02g - decision-making.qmd
      - 02h - adaptations.qmd
      - 02i - metrics.qmd
    - part: app 0 cover.qmd
      chapters: 
      - app A assessment-questionnaires.qmd
      - app B implementation-templates.md
      - app C regulatory-reference.md
      - app D case-studies.md
      - app E field-data-template.md
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty


